#!/system/bin/sh

KERNEL=$(cat /proc/version)

cat /system/jolla-kernel.info > /data/kernel.ota.prop

sed -i '/fullver/d' /data/kernel.ota.prop
sed -i '/\}/d' /data/kernel.ota.prop
echo \ \ \ \ \"fullver\"\: \"$KERNEL\" >> /data/kernel.ota.prop
echo \} >> /data/kernel.ota.prop
